// <auto-generated />
namespace MvcPossAppDatabseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialstate));
        
        string IMigrationMetadata.Id
        {
            get { return "201908191727548_initialstate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
